### ISSUE TITLE
Switching python back to lecture site

### ISSUE THREAD

**Issue by DrDrij** [QuantEcon/lecture-python-website#11]
**To switch between between the python lecture site and the new python landing page at `python.quantecon.org` you need to remove one of the following records and add the other.**

All the settings are made in Route53 on the AWS Console: https://console.aws.amazon.com/route53/home?region=ap-southeast-2#resource-record-sets:Z1Q6W7J7TUQ68R

eg. To revert the python lecture site, delete the `python.quantecon.org - CNAME` record and create a new `python.quantecon.org - A` record set.

We have been using an A record pointing `python.quantecon.org` => Cloudfront `d6mtww49nma8j.cloudfront.net` => S3 `python.quantecon.org.s3-website-ap-southeast-2.amazonaws.com`

 **Name:** python.quantecon.org
**Type:** A - IPv4 address
**Alias:** Yes
**Alias Target:** d6mtww49nma8j.cloudfront.net.
Hit **Save Record Set**

![image](https://user-images.githubusercontent.com/5886045/77645325-a7502580-6fb6-11ea-9ee8-e17b77350188.png)

We will now use a CNAME pointing `python.quantecon.org` => GitHub Pages `quantecon.github.io`

 **Name:** python.quantecon.org
**Type:** CNAME - Canonical name
**Alias:** No
**Alias Target:** quantecon.github.io
Hit **Save Record Set**

![image](https://user-images.githubusercontent.com/5886045/77645731-54c33900-6fb7-11ea-81fd-607de95853f1.png)

**Comment by mmcky** [comment]
thanks @DrDrij

**Comment by mmcky** [comment]
Thanks @DrDrij -- this work is now complete.
