### ISSUE TITLE
Small adjustment to 2nd level pages

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-website#15]
On the page

https://python-intro.quantecon.org/

could we please have the "Open source lectures" heading removed and the GitHub box combined with the other two, so there are three boxes under "Other ways to...".

Please remove the sentence "Readers can view the source... changes)"

The same for the other two (programming and advanced).

**Comment by jstac** [comment]
Ah, and the link from that GH box is outdated!  It leads to the old lecture site repo.  Adding high priority.

**Comment by DrDrij** [comment]
Will fix this morning.

**Comment by DrDrij** [comment]
https://github.com/QuantEcon/lecture-python-intro/pull/105
https://github.com/QuantEcon/lecture-python-programming/pull/30
https://github.com/QuantEcon/lecture-python-advanced/pull/110

**Comment by mmcky** [comment]
> so there are three boxes under "Other ways to...".

@DrDrij There are currently two boxes. Do we need to add in the `GitHub` box? i only see two boxes under the "Other ways to...". Is this issue old -- did we decided to remove the GitHub box elsewhere?

**Comment by mmcky** [comment]
@jstac is this resolved?I don't see any GitHub box. Did we decide to remove somewhere else?
