### ISSUE TITLE
Name List for Contributors Page

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-website#2]
This is the name list of people who contributed to QuantEcon.
[Name_List.xlsx](https://github.com/QuantEcon/lecture-source-py/files/4341600/Name_List.xlsx)

**Comment by mmcky** [comment]
@DrDrij perhaps this contributor page can be setup in this general level repository.

**Comment by jstac** [comment]
Copy and pasting from slack, regarding python.quantecon.org, I wrote

 "So, my proposal is that we have, perhaps in/after that text at the top ("A series of lectures") a link that says "Read more" or "About these lectures".  Then, it links to a subpage that gives background plus general troubleshooting info that applies to all three lecture series."

I suggest that we put all these names in that subpage, in a section titled "Contributors".

It will be separate from and complement the GH compiled contributors pages on the three individual sites.

**Comment by mmcky** [comment]
thanks for posting that here @jstac

**Comment by mmcky** [comment]
This is  now done - so closing. @sayaikegawa is setting up links from the lecture pages to this `contributor` page hosted on `orgsite`
