### ISSUE TITLE
Should we change all Python code-block directives to ipython3?

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-website#20]
It's easy to forget and use `python3` when you also use a cell magic.

(I usually copy and paste from the code block above.)

Should `ipython3` be the default?  Is there a downside to that change?

CC @mmcky @AakashGfude

**Comment by Harveyt47** [comment]
Hi @jstac @shlff @mtiley this issue about making all code blocks `.. code-block:: ipython3` in rst files? Just want to clarify before I dive into the issue.

**Comment by mmcky** [comment]
`ipython3` is treated as a language synonym so fine to update
https://github.com/QuantEcon/lecture-python-intro/blob/f43f0986221c9bb75397971d6d45ba83f010ec8a/conf.py#L421

**Comment by jstac** [comment]
It's probably a good idea to be consistent and use `ipython3` throughout.

But, on the other hand, this change will touch many lectures.  That's a bit of an issue.  

Now I think about it, let's forget about this for now.
