### ISSUE TITLE
use quantecon's rank_size_plot

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-website#38]
Do a search for all rst files that contain `rank_size`.

Replace the rank size plotting code there with the code in [this PR](https://github.com/QuantEcon/QuantEcon.py/pull/518) as soon as it is merged.

**Comment by Harveyt47** [comment]
Hi @jstac I can only see rank size plots in the following lectures. 

[Heavy-Tailed Distributions](https://python-intro.quantecon.org/heavy_tails.html#Exercise-4) this lecture uses log on the variables then plots those log variables while the PR you link uses `ax.loglog()`.

[Wealth Distribution Dynamics](https://python-intro.quantecon.org/wealth_dynamics.html#Exercise-2) this lecture uses log on the variables then plots those log variables while the PR you link uses `ax.loglog()`

[Kesten Processes and Firm Dynamics
](https://python-intro.quantecon.org/kesten_processes.html#Exercise-4) This lecture uses the QuantEcon.py library

 Do you prefer the use of `ax.loglog()` over log on the variables?

**Comment by jstac** [comment]
Yes, thanks @Harveyt47,  the first two should be changed to use the quantecon Python library.

In each case, the code that generates a rank size plot from the data should be removed and the function `qe.rank_size_plot` should be used -- the data should be passed directly to this function.  When the exercise is stated, the reader should be informed of the existence of this library function.

**Comment by Harveyt47** [comment]
Thanks @jstac I see now. 
1) I will add a reference of the functions existance as well as a link to the documentation to the exercise question.

2) I will also remove the code of the function from the answer and call the function via `qe.rank_size_plot`.
