### ISSUE TITLE
`make view` fails with Sphinx error - maybe related to symlink?

### ISSUE THREAD

**Issue by Jacob-Bishop** [QuantEcon/lecture-python-website#42]
Hi All, 

I tried to download these lectures following the instructions in this repo's readme, using Windows 10 and gnuwin32's Make for Windows. I've cloned the repo with symlinks enabled  (-c core.symlinks=true).

When I run `make notebooks`, I get a warning "WARNING: jupyter_static_path entry C:\[my path]\lecture-source-py\_static does not exist", and then when I try to run `make view`, I get the following error:
Sphinx error:
Builder name view not registered or available through entry point
make: *** [view] Error 2

Anyone have ideas about what might be going wrong?

**Comment by mmcky** [comment]
@Jacob-Bishop and @gen-li you should be able to use [jupinx](https://jupinx.quantecon.org) to compile these lecture sets. We have a lot of changes recently and split the lecture series. So let me know if you are still wanting to compile the lectures as notebooks etc. and I can assist.
