### ISSUE TITLE
Fonts in MacTex not available as system fonts

### ISSUE THREAD

**Issue by AakashGfude** [QuantEcon/lecture-python-website#45]
Non-standard Fonts which are required by [lecture-source-py](https://github.com/QuantEcon/lecture-source-py) and being packaged with MacTex, like CMU Serif and Liberation Mono, are not automatically able as system fonts. 
The following resource walks through the steps to make it available as system fonts in Linux:-   http://latex.silmaril.ie/formattinginformation/fontuse.html. But no concrete solution is found yet for Macbook.  @shlff installed it in his system directly from the internet which can be a quick solution for now, but not ideal.

**Comment by AakashGfude** [comment]
@Harveyt47 I think this can be closed.

**Comment by shlff** [comment]
Thanks, @AakashGfude and @Harveyt47 . I will close it.
