### ISSUE TITLE
Update GitHub Actions - use minimal theme if private theme not available.

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-website#67]
@jstac @shizejin the preview is not working here as private credentials for fetching the `private` theme are not available for PR's coming from forks. I will try and update the script if `private` theme is not available to build the preview using the default `minimal` theme

_Originally posted by @mmcky in https://github.com/QuantEcon/lecture-python/pull/214#issuecomment-629892256_

**Comment by mmcky** [comment]
This is now implemented in `lecture-python`

Need to add to:

- [x] programming
- [x] advanced

**Comment by mmcky** [comment]
@najuzilu do you think you might be able to migrate these changes to the other repos?

**Comment by najuzilu** [comment]
@mmcky :+1:

**Comment by najuzilu** [comment]
Github Actions have been added for the following repos:
- programming [see merged PR](https://github.com/QuantEcon/lecture-python-programming/pull/58)
- advanced [see merged PR](https://github.com/QuantEcon/lecture-python-advanced/pull/132)

**Comment by mmcky** [comment]
thanks @najuzilu
