### ISSUE TITLE
Archive Repository and Migrate Issues

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-website#70]
this repository needs to be archived as old infrastructure

- [ ] migrate issues

**Comment by mmcky** [comment]
@DrDrij is there anything in this repo you'd like to preserve?

**Comment by DrDrij** [comment]
I've taken a final pull. Thanks @mmcky

**Comment by mmcky** [comment]
thanks @DrDrij all issues migrated so will archive this now.
