### ISSUE TITLE
Add a Contributors page for Projects

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-website#8]
It has been agreed that the licence content should be switched to https://creativecommons.org/licenses/by-sa/4.0/.

Steps 

1. change the footer in the lectures.
2. remove all co-author statements --- has to be done carefully because the wording varies so it's hard to search.
3. add a contributors page like [this one](https://datascience.quantecon.org/contributors.html), at first with a few sentences describing their contributions.  

Regarding 3, we should also look into automatically providing data on each contributors value added via GH.  Also, we should make sure that every name we take out of the RST files ends up on the contributor page.  Finally, we should shift [this info](https://python.quantecon.org/about_lectures.html#Credits) onto the same page, perhaps at the bottom as extra information.

**Comment by mmcky** [comment]
This is done. See https://github.com/QuantEcon/lecture-python-website/issues/2
